"""The agent summary: one standing instruction per defence, in a generated region of a file."""

from __future__ import annotations

from typing import TYPE_CHECKING

from python_qa.finding import Finding

if TYPE_CHECKING:
    from python_qa.config import Config
    from python_qa.defences import Defence
    from python_qa.record import RecordEntry

STALE = "pyqaci.summary.stale"
BEGIN = "<!-- BEGIN python-qa summary: generated by `python-qa summary`, do not edit -->"
END = "<!-- END python-qa summary -->"
_TOOL_NAMES = {"pylint": "Pylint", "python-qa": "python-qa"}


def render(defences: list[Defence], entries: list[RecordEntry], config: Config) -> str:
    """Return the region: the bespoke defences one per line, the catalogues counted."""
    lines = [
        BEGIN,
        "## Defences enforced by python-qa",
        "",
        "Run `python-qa run` before committing. `python-qa rule-doc <identifier>` prints the "
        "documentation for any identifier a finding prints, offline.",
        "",
    ]
    for defence in defences:
        if defence.tool not in _TOOL_NAMES:
            continue
        source = _TOOL_NAMES[defence.tool]
        if defence.tool != "python-qa":
            source = f"{source}, {defence.origin}"
        lines.append(
            f"- `{defence.identifier}` ({source}): {defence.summary} Docs: `{defence.doc}`"
        )
    ruff = sum(1 for defence in defences if defence.tool == "ruff")
    mypy = sum(1 for defence in defences if defence.tool == "mypy")
    exceptions = "exception" if len(entries) == 1 else "exceptions"
    lines.extend(
        [
            f"- {ruff} Ruff rules and {mypy} mypy error codes also block; `python-qa rules` "
            "lists every one.",
            f"- Never suppress a finding without an exception in the project record: "
            f"{len(entries)} {exceptions} in `{config.record.path}`, listed by "
            "`python-qa record list`.",
            END,
        ]
    )
    return "\n".join(lines)


def place(text: str, region: str) -> str:
    """Return text with its generated region replaced by region, or region appended."""
    start, end = text.find(BEGIN), text.find(END)
    if start != -1 and end > start:
        return text[:start] + region + text[end + len(END) :]
    if not text:
        return region + "\n"
    return text.rstrip("\n") + "\n\n" + region + "\n"


def write_summary(config: Config, defences: list[Defence], entries: list[RecordEntry]) -> None:
    """Write the region into the configured file, creating the file if needed."""
    if config.summary_file is None:
        return
    path = config.root / config.summary_file
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    path.write_text(place(text, render(defences, entries, config)), encoding="utf-8")


def check_summary(
    config: Config, defences: list[Defence], entries: list[RecordEntry]
) -> list[Finding]:
    """Report a region that differs from what would be generated now."""
    if config.summary_file is None:
        return []
    path = config.root / config.summary_file
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    if place(text, render(defences, entries, config)) == text:
        return []
    return [
        Finding(
            config.summary_file,
            0,
            STALE,
            "the generated summary is out of date; run `python-qa summary` and commit it",
        )
    ]
